spring.application.name=kavachdms

spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.udfhvrbjibebsgaujesp
spring.datasource.password=sykdig-Jimzij-2nagfa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}

minio.endpoint=${MINIO_ENDPOINT:localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket=${MINIO_BUCKET:documents}
minio.secure=${MINIO_SECURE:false}
minio.url=http://localhost:9000

# Hyperledger Fabric
fabric.connection-profile=${FABRIC_CONNECTION_PROFILE:}
fabric.certificate=${FABRIC_CERTIFICATE:}
fabric.private-key=${FABRIC_PRIVATE_KEY:}
fabric.msp-id=${FABRIC_MSP_ID:}
fabric.channel=${FABRIC_CHANNEL:}
fabric.chaincode=${FABRIC_CHAINCODE:}

fabric.gateway-endpoint=${FABRIC_GATEWAY_ENDPOINT:}
fabric.tls-certificate=${FABRIC_TLS_CERTIFICATE:}